export const missionInputsData = [
    {
        control: "input",
        type: "text",
        name: "title",
        placeholder: "Mission Header",
        placeholderAr: "Mission Header",
        className: 'block md:w-full w-[100%] ',
        containerClassName: 'block w-full'
    },
    {
        control: "input",
        type: "text",
        name: "titleAr",
        placeholder: "Mission Header (Arabic)",
        placeholderAr: "Mission Header (Arabic)",
        className: 'block md:w-full w-[100%] ',
        containerClassName: 'block w-full',
        dir: 'rtl',
    },
    {
        control: "textarea",
        name: "disc",
        placeholder: "Mission Description",
        placeholderAr: "Mission Description",
        className: 'block md:w-full ',
        rows:5,
    },
    {
        control: "textarea",
        name: "discAr",
        placeholder: "Mission Description (Arabic)",
        placeholderAr: "Mission Description (Arabic)",
        className: 'block md:w-full ',
        rows:5,
        dir: 'rtl',
    },
]
export const visionInputsData = [
    {
        control: "input",
        type: "text",
        name: "title",
        placeholder: "Vision Header",
        placeholderAr: "Vision Header",
        className: 'block md:w-full w-[100%] ',
        containerClassName: 'block w-full'
    },
    {
        control: "input",
        type: "text",
        name: "titleAr",
        placeholder: "Vision Header (Arabic)",
        placeholderAr: "Vision Header (Arabic)",
        className: 'block md:w-full w-[100%] ',
        containerClassName: 'block w-full',
        dir: 'rtl',
    },
    {
        control: "textarea",
        name: "disc",
        placeholder: "Vision Description",
        placeholderAr: "Vision Description",
        className: 'block md:w-full ',
        rows:5,
    },
    {
        control: "textarea",
        name: "discAr",
        placeholder: "Vision Description (Arabic)",
        placeholderAr: "Vision Description (Arabic)",
        className: 'block md:w-full ',
        rows:5,
        dir: 'rtl',
    },
]
