

export const productInputsData = [
    {
        control: "textarea",
        name: "disc",
        placeholder: "Service Short Description",
        placeholderAr: "Service Short Description",
        className: 'block md:w-full ',
        rows: 5,
    },
    {
        control: "textarea",
        name: "discAr",
        placeholder: "Service Short Description (Arabic)",
        placeholderAr: "Service Short Description (Arabic)",
        className: 'block md:w-full ',
        rows: 5,
        dir: 'rtl',
    },

]

export const productsTitleInput = [
    {
        control: "input",
        type: "text",
        name: "title",
        placeholder: "Services Header",
        placeholderAr: "Services Header",
        className: 'block md:w-full w-[100%] ',
        containerClassName: 'block w-full'
    },
    {
        control: "input",
        type: "text",
        name: "titleAr",
        placeholder: "Services Header (Arabic)",
        placeholderAr: "Services Header (Arabic)",
        className: 'block md:w-full w-[100%] ',
        containerClassName: 'block w-full',
        dir: 'rtl',
    },
    {
        control: "textarea",
        name: "disc",
        placeholder: "Services Description",
        placeholderAr: "Services Description",
        className: 'block md:w-full',
        rows: 4,
    },
    {
        control: "textarea",
        name: "discAr",
        placeholder: "Services Description (Arabic)",
        placeholderAr: "Services Description (Arabic)",
        className: 'block md:w-full',
        rows: 4,
        dir: 'rtl',
    },
]

export const serviceDetailInputs = [
    {
        control: "input",
        type: "text",
        name: "title",
        placeholder: "Service Title",
        placeholderAr: "Service Title",
        className: 'block md:w-full w-[100%]',
        containerClassName: 'block w-full'
    },
    {
        control: "input",
        type: "text",
        name: "titleAr",
        placeholder: "Service Title (Arabic)",
        placeholderAr: "Service Title (Arabic)",
        className: 'block md:w-full w-[100%]',
        containerClassName: 'block w-full',
        dir: 'rtl',
    },
    {
        control: "input",
        type: "text",
        name: "label",
        placeholder: "Small Label",
        placeholderAr: "Small Label",
        className: 'block md:w-full w-[100%]',
        containerClassName: 'block w-full'
    },
    {
        control: "input",
        type: "text",
        name: "labelAr",
        placeholder: "Small Label (Arabic)",
        placeholderAr: "Small Label (Arabic)",
        className: 'block md:w-full w-[100%]',
        containerClassName: 'block w-full',
        dir: 'rtl',
    },
    {
        control: "textarea",
        name: "disc",
        placeholder: "Card Short Description",
        placeholderAr: "Card Short Description",
        className: 'block md:w-full',
        rows: 4,
    },
    {
        control: "textarea",
        name: "discAr",
        placeholder: "Card Short Description (Arabic)",
        placeholderAr: "Card Short Description (Arabic)",
        className: 'block md:w-full',
        rows: 4,
        dir: 'rtl',
    },
    {
        control: "textarea",
        name: "lead",
        placeholder: "Service Page Intro",
        placeholderAr: "Service Page Intro",
        className: 'block md:w-full',
        rows: 5,
    },
    {
        control: "textarea",
        name: "leadAr",
        placeholder: "Service Page Intro (Arabic)",
        placeholderAr: "Service Page Intro (Arabic)",
        className: 'block md:w-full',
        rows: 5,
        dir: 'rtl',
    },
    {
        control: "textarea",
        name: "whatWeBuild",
        placeholder: "What We Build - one item per line",
        placeholderAr: "What We Build - one item per line",
        className: 'block md:w-full',
        rows: 6,
    },
    {
        control: "textarea",
        name: "whatWeBuildAr",
        placeholder: "What We Build (Arabic) - one item per line",
        placeholderAr: "What We Build (Arabic) - one item per line",
        className: 'block md:w-full',
        rows: 6,
        dir: 'rtl',
    },
    {
        control: "textarea",
        name: "deliverables",
        placeholder: "Deliverables - one item per line",
        placeholderAr: "Deliverables - one item per line",
        className: 'block md:w-full',
        rows: 5,
    },
    {
        control: "textarea",
        name: "deliverablesAr",
        placeholder: "Deliverables (Arabic) - one item per line",
        placeholderAr: "Deliverables (Arabic) - one item per line",
        className: 'block md:w-full',
        rows: 5,
        dir: 'rtl',
    },
    {
        control: "textarea",
        name: "sectors",
        placeholder: "Sectors - one item per line",
        placeholderAr: "Sectors - one item per line",
        className: 'block md:w-full',
        rows: 5,
    },
    {
        control: "textarea",
        name: "sectorsAr",
        placeholder: "Sectors (Arabic) - one item per line",
        placeholderAr: "Sectors (Arabic) - one item per line",
        className: 'block md:w-full',
        rows: 5,
        dir: 'rtl',
    },
    {
        control: "textarea",
        name: "proof",
        placeholder: "Bottom Paragraph",
        placeholderAr: "Bottom Paragraph",
        className: 'block md:w-full',
        rows: 5,
    },
    {
        control: "textarea",
        name: "proofAr",
        placeholder: "Bottom Paragraph (Arabic)",
        placeholderAr: "Bottom Paragraph (Arabic)",
        className: 'block md:w-full',
        rows: 5,
        dir: 'rtl',
    },
]
